---
- name: Add Elasticsearch GPG key.
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic repository.
  template:
    src: elastic.repo.j2
    dest: "/etc/yum.repos.d/elastic-{{ logstash_version }}.repo"
    mode: 0644

- name: Install Logstash.
  package:
    name: '{{ logstash_package }}'
    state: present
